---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 25763.
--- DateTime: 2025/5/10 13:40
---
-- 参数说明：
-- KEYS[1] 是 Redis 中的 ZSET 键
-- ARGV[1] 是用户的 ID
-- ARGV[2] 是当前时间戳

local key = KEYS[1]
local userId = ARGV[1]
local timestamp = tonumber(ARGV[2])

-- 检查用户是否已经点赞
local score = redis.call('ZSCORE', key, userId)

if score == false then
    -- 用户未点赞，执行点赞操作
    redis.call('ZADD', key, timestamp, userId)
    return 1 -- 返回 1 表示点赞成功
else
    -- 用户已点赞，执行取消点赞操作
    redis.call('ZREM', key, userId)
    return 0 -- 返回 0 表示取消点赞成功
end